import fs from "node:fs";
import path from "node:path";

/**
 * Loader for the weekly agenda proposals (scripts/propose-agenda.mjs
 * output under proposals/agenda/<runId>/<case>.md). Proposals are ideas,
 * not content: nothing here enters the ledger, and the page that renders
 * them says so. The parser targets the exact format renderProposalFile
 * emits (the roundtrip is pinned by tests); a block that does not parse
 * is skipped and counted, never guessed at, and never breaks the build —
 * a malformed proposal is a lost suggestion, not a lost site.
 */

export interface AgendaProposal {
  kind: string;
  title: string;
  question: string;
  closestExisting: string[];
  gap: string;
  wouldSettle: string;
  effortTier: string;
}

export interface ProposalFile {
  caseSlug: string;
  runId: string;
  date: string;
  model: string;
  promptVersion: string;
  proposals: AgendaProposal[];
  skippedBlocks: number;
}

export interface ProposalRun {
  runId: string;
  date: string;
  files: ProposalFile[];
}

const AGENDA_DIR = path.join(process.cwd(), "proposals", "agenda");

/** Parse one proposal file body (format: scripts/lib/agenda-propose.mjs). */
export function parseProposalFile(caseSlug: string, text: string): ProposalFile {
  const meta = {
    runId: text.match(/runId (\S+?),/)?.[1] ?? "unknown",
    date: text.match(/^# Agenda proposals — .+ — (\d{4}-\d{2}-\d{2})/m)?.[1] ?? "unknown",
    model: text.match(/Generated by (.+?), runId/)?.[1] ?? "unknown",
    promptVersion: text.match(/promptVersion (\S+?),/)?.[1] ?? "unknown",
  };
  const proposals: AgendaProposal[] = [];
  let skippedBlocks = 0;
  const blocks = text.split(/^## /m).slice(1);
  for (const block of blocks) {
    const head = block.match(/^\d+\. \[([a-z-]+)\] (.+)$/m);
    const question = block.match(/\*\*Question \/ truth condition:\*\* ([\s\S]+?)\n\n/)?.[1];
    const closest = block.match(/\*\*Closest existing:\*\* (.+?) — ([\s\S]+?)\n\n/);
    const wouldSettle = block.match(/\*\*What it would settle:\*\* ([\s\S]+?)\n\n/)?.[1];
    const effort = block.match(/\*\*Effort:\*\* (\S+)/)?.[1];
    if (!head || !question || !closest || !wouldSettle || !effort) {
      skippedBlocks += 1;
      continue;
    }
    proposals.push({
      kind: head[1],
      title: head[2].trim(),
      question: question.replace(/\s+/g, " ").trim(),
      closestExisting: closest[1].split(",").map((s) => s.trim()),
      gap: closest[2].replace(/\s+/g, " ").trim(),
      wouldSettle: wouldSettle.replace(/\s+/g, " ").trim(),
      effortTier: effort.trim(),
    });
  }
  return { caseSlug, ...meta, proposals, skippedBlocks };
}

/** All proposal runs, newest first; [] when none exist yet. */
export function loadProposalRuns(): ProposalRun[] {
  if (!fs.existsSync(AGENDA_DIR)) return [];
  return fs
    .readdirSync(AGENDA_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()
    .reverse()
    .map((runId) => {
      const dir = path.join(AGENDA_DIR, runId);
      const files = fs
        .readdirSync(dir)
        .filter((f) => f.endsWith(".md") && f !== "report.md")
        .sort()
        .map((f) =>
          parseProposalFile(f.replace(/\.md$/, ""), fs.readFileSync(path.join(dir, f), "utf8")),
        )
        .filter((pf) => pf.proposals.length > 0 || pf.skippedBlocks > 0);
      const date = files[0]?.date ?? runId.slice(0, 10);
      return { runId, date, files };
    })
    .filter((run) => run.files.length > 0);
}
